### ISSUE TITLE
package com.singularsys.jep.Jep does not exist

### ISSUE THREAD

**Issue by Klodovskyy** [nathanfunk/jep-java-gpl#1]
Mr Nathan,

I've been trying to use jep in my java program using a simple parse&evaluate syntax but the package wasn't found. 

I've already generated the .jar file and added it to my class path.

Here's my code : 

******************************************************************************************
import com.singularsys.jep.Jep;
/**
 *
 * @author asus
 */
public class Jep
extends java.lang.Object
implements java.io.Serializable {

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    Jep jep = new Jep();
    try {
        jep.addVariable("x", 10);
        jep.parse("x+1");
        Object result = jep.evaluate();
 			
        System.out.println("x + 1 = " + result);
        } catch (JepException e) {
        System.out.println("An error occurred: " + e.getMessage());
        }
        
    }
}

******************************************************************************************

What I'm I missing ? Please try to update the documentation for 1st time users.

**Comment by RichardMorris** [comment]
I think you have two different Jep classes. The main  com.singularsys.jep.Jep one and your local class Jep declared as

```
public class Jep extends java.lang.Object implements java.io.Serializable {...
```
Rename your class to something other than Jep and you should hopefully resolve your issue.

**Comment by Klodovskyy** [comment]
Can you please send me a code sample (starting from package import ) ? I found many refs online like com.singularsys.jep.Jep / org.nfunk.jep etc .. which is confusing , I have the generated jep-x-x-x.jar though and I followed the installation guide but there isn't much docs of how to use it , a any simple example will be appreciated !

**Comment by RichardMorris** [comment]
This repository uses is the older opensource version of the package. For that the main package is
`org.nfunk.jep` and the main class is `org.nfunk.jep.JEP`.
The newer 3.4, 3.5 versions are closed source, this is available from http://singularsys.com/jep/. These was a major reenginering between the two version and the newer version have a main package `com.singularsys.jep` and the main class is  `com.singularsys.jep.Jep`.
You can use most of the features documented in the newer version, just change the package back to the old one and use JEP rather than Jep.

The full document for the older code should be in the doc/html directory of the code you download. Just open the index.html file in that directory. You may need to regenerate the javadoc from the source tree.

**Comment by RichardMorris** [comment]
There are two main version of Jep

- The older open source version 2.4.1 in this respoitory. This has the main package `org.nfunk.jep` and main class `org.nfunk.jep.JEP`. 
- The new version 3.4, 3.5 which is closed source. There the main package is `com.singularsys.jep` and the main class is `com.singularsys.Jep`

The document for the older version can be viewed at  http://htmlpreview.github.io/?https://github.com/nathanfunk/jep-java-gpl/blob/master/doc/html/index.html you should also find it in the doc/html directory of your local copy of the respository. You will need to regenerate the JavaDoc if you want to see that.

**Comment by RichardMorris** [comment]
The simplest test example can be found at https://github.com/nathanfunk/jep-java-gpl/blob/master/src/org/nfunk/jepexamples/SimpleTest.java there are a few more examples in the same package.

**Comment by Klodovskyy** [comment]
Thanks! one last question please , can the org.nfunk.jep package handle parsing/evaluating Python methods & importing some of it's librairies ?

**Comment by Klodovskyy** [comment]
That's the main reason why I'm using JEP, to import and run some Python libs in java code, the fact that some references or most of them are talking about mathematical experessions is a bit confusing !

**Comment by RichardMorris** [comment]
I think you might have the wrong product entirely. This is Jep: the Java Expression Parser it job is all about parsing mathematical expressions. I think you want https://pypi.org/project/jep/

**Comment by Klodovskyy** [comment]
yeah I definitely confounded between these two. Thanks!
